# presentation_output.R
# =============================================================
# Master-thesis mid-term presentation: build all figure PDFs and
# LaTeX tables that `presentation/main.tex` consumes via
# \includegraphics{...} and \input{...}.
#
# Run from the project root:
#   Rscript presentation_output.R
#
# Sources the full data pipeline (data preparation -> empirical
# regressions -> plot definitions) and then writes:
#   presentation/figures/*.pdf
#   presentation/tables/*.tex   (booktabs tabulars, no float wrapper)
# =============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(tibble)
})

OUT_DIR <- "presentation"
FIG_DIR <- file.path(OUT_DIR, "figures")
TAB_DIR <- file.path(OUT_DIR, "tables")
dir.create(FIG_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(TAB_DIR, recursive = TRUE, showWarnings = FALSE)

# -------------------------------------------------------------
# 1. Run the pipeline. Each script is sourced into the global
#    environment so downstream objects are visible.
# -------------------------------------------------------------
source("data preperation.R")
source("empirical.R")
source("plots.R")

# -------------------------------------------------------------
# 2. Save every plot defined in `plots` to figures/
# -------------------------------------------------------------
save_all_plots(dir = FIG_DIR, width = 9, height = 6)

# -------------------------------------------------------------
# 3. LaTeX-table helpers (no kableExtra dependency)
# -------------------------------------------------------------
fmt_num <- function(x, digits = 3) {
  ifelse(is.na(x), "--", formatC(x, format = "f", digits = digits))
}
fmt_pct <- function(x, digits = 1) {
  ifelse(is.na(x), "--", paste0(formatC(100 * x, format = "f", digits = digits), "\\%"))
}
fmt_int <- function(x) ifelse(is.na(x), "--", formatC(x, format = "d", big.mark = ","))
star <- function(p) {
  ifelse(is.na(p), "",
  ifelse(p < 0.01, "$^{***}$",
  ifelse(p < 0.05, "$^{**}$",
  ifelse(p < 0.10, "$^{*}$", ""))))
}

# Build a booktabs tabular (no caption / float -- wrap in beamer)
write_tabular <- function(rows, header, align, file) {
  body <- vapply(seq_len(nrow(rows)),
                 function(i) paste0(paste(rows[i, ], collapse = " & "), " \\\\"),
                 character(1))
  lines <- c(
    "% auto-generated by presentation_output.R; do not edit",
    sprintf("\\begin{tabular}{%s}", align),
    "\\toprule",
    paste0(paste(header, collapse = " & "), " \\\\"),
    "\\midrule",
    body,
    "\\bottomrule",
    "\\end{tabular}"
  )
  writeLines(lines, file.path(TAB_DIR, file))
}

# -------------------------------------------------------------
# 4. Eq (18): rx ~ CF, per country
# -------------------------------------------------------------
eq18_rows <- tab_18 %>%
  filter(term == "CF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\beta$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq),
    `$T$`    = fmt_int(T_obs)
  )

write_tabular(
  rows   = as.matrix(eq18_rows),
  header = colnames(eq18_rows),
  align  = "lrrrrr",
  file   = "eq18_local_cf.tex"
)

# -------------------------------------------------------------
# 5. Eq (20): rx ~ GCF, per country
# -------------------------------------------------------------
eq20_rows <- tab_20 %>%
  filter(term == "GCF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\gamma$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq),
    `$T$`    = fmt_int(T_obs)
  )
write_tabular(
  rows   = as.matrix(eq20_rows),
  header = colnames(eq20_rows),
  align  = "lrrrrr",
  file   = "eq20_global_cf.tex"
)

# -------------------------------------------------------------
# 6. Eq (19): rx ~ CF + GCF -- subsumption test per country
# -------------------------------------------------------------
eq19_wide <- tab_19 %>%
  filter(term %in% c("CF", "GCF")) %>%
  select(country, term, estimate, std_err, p_value, r_sq) %>%
  pivot_wider(names_from = term,
              values_from = c(estimate, std_err, p_value)) %>%
  left_join(
    nested_local_per_country %>% select(country, p_wald = p_value),
    by = "country"
  ) %>%
  arrange(country)

eq19_rows <- eq19_wide %>%
  transmute(
    Country = country,
    `$\\hat\\beta_{CF}$`   = paste0(fmt_num(estimate_CF, 3),  star(p_value_CF)),
    `(SE)`                 = paste0("(", fmt_num(std_err_CF, 3), ")"),
    `$\\hat\\gamma_{GCF}$` = paste0(fmt_num(estimate_GCF, 3), star(p_value_GCF)),
    `(SE) `                = paste0("(", fmt_num(std_err_GCF, 3), ")"),
    `$R^2$`                = fmt_pct(r_sq),
    `Wald $p$`             = fmt_num(p_wald, 3)
  )
write_tabular(
  rows   = as.matrix(eq19_rows),
  header = colnames(eq19_rows),
  align  = "lrrrrrr",
  file   = "eq19_subsumption.tex"
)

# -------------------------------------------------------------
# 7. Eq (22) & (23): USD investor view -- GCF and FXGCF
# -------------------------------------------------------------
eq22_rows <- tab_22 %>%
  filter(term == "GCF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\gamma$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq)
  )
write_tabular(
  rows   = as.matrix(eq22_rows),
  header = colnames(eq22_rows),
  align  = "lrrrr",
  file   = "eq22_usd_gcf.tex"
)

eq23_rows <- tab_23 %>%
  filter(term == "FXGCF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\delta$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq)
  )
write_tabular(
  rows   = as.matrix(eq23_rows),
  header = colnames(eq23_rows),
  align  = "lrrrr",
  file   = "eq23_usd_fxgcf.tex"
)

# -------------------------------------------------------------
# 8. Pooled panel (Driscoll-Kraay): one row per spec
# -------------------------------------------------------------
pull_dk <- function(res, label, term) {
  ct <- res$coeftest
  if (!(term %in% rownames(ct))) {
    return(tibble(spec = label, term = term,
                  estimate = NA, se = NA, t = NA, p = NA))
  }
  tibble(
    spec     = label,
    term     = term,
    estimate = ct[term, "Estimate"],
    se       = ct[term, "Std. Error"],
    t        = ct[term, "t value"],
    p        = ct[term, "Pr(>|t|)"]
  )
}
panel_tbl <- bind_rows(
  pull_dk(panel_18, "Eq (18): rx $\\sim$ CF",            "CF"),
  pull_dk(panel_19, "Eq (19): rx $\\sim$ CF + GCF",      "CF"),
  pull_dk(panel_19, "Eq (19): rx $\\sim$ CF + GCF",      "GCF"),
  pull_dk(panel_20, "Eq (20): rx $\\sim$ GCF",           "GCF"),
  pull_dk(panel_21, "Eq (21): rx$^{USD}\\sim$ CF + GCF", "CF"),
  pull_dk(panel_21, "Eq (21): rx$^{USD}\\sim$ CF + GCF", "GCF"),
  pull_dk(panel_22, "Eq (22): rx$^{USD}\\sim$ GCF",      "GCF"),
  pull_dk(panel_23, "Eq (23): rx$^{USD}\\sim$ FXGCF",    "FXGCF")
)

panel_rows <- panel_tbl %>%
  transmute(
    Specification = spec,
    Term          = term,
    Estimate      = paste0(fmt_num(estimate, 3), star(p)),
    `DK SE`       = fmt_num(se, 3),
    `$t$`         = fmt_num(t, 2)
  )
write_tabular(
  rows   = as.matrix(panel_rows),
  header = colnames(panel_rows),
  align  = "llrrr",
  file   = "panel_dk.tex"
)

# -------------------------------------------------------------
# 9. Out-of-sample tests: Clark-West and Diebold-Mariano
# -------------------------------------------------------------
cw_rows <- bind_rows(
  cw_local %>% transmute(
    Country = country,
    Test    = "rx: GCF vs CF+GCF (CW)",
    `$\\Delta$MSPE-adj` = fmt_num(cw_mean, 4),
    `$t$`               = fmt_num(cw_t, 2),
    `$p$ (1-sided)`     = fmt_num(cw_p_one_sided, 3)
  ),
  cw_usd %>% transmute(
    Country = country,
    Test    = "rx$^{USD}$: GCF vs CF+GCF (CW)",
    `$\\Delta$MSPE-adj` = fmt_num(cw_mean, 4),
    `$t$`               = fmt_num(cw_t, 2),
    `$p$ (1-sided)`     = fmt_num(cw_p_one_sided, 3)
  )
) %>% arrange(Test, Country)

write_tabular(
  rows   = as.matrix(cw_rows),
  header = colnames(cw_rows),
  align  = "llrrr",
  file   = "oos_clark_west.tex"
)

dm_rows <- cw_fxgcf %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `DM mean ($e^2_{GCF}-e^2_{FXGCF}$)` = fmt_num(dm_mean, 4),
    `$t$`             = fmt_num(dm_t, 2),
    `$p$ (2-sided)`   = fmt_num(dm_p_two_sided, 3),
    `$n_{fcst}$`      = fmt_int(n_forecasts)
  )
write_tabular(
  rows   = as.matrix(dm_rows),
  header = colnames(dm_rows),
  align  = "lrrrr",
  file   = "oos_dm_fxgcf.tex"
)

# -------------------------------------------------------------
# 10. US replication: CP-2015 (CF) vs CP-2005 (forwards)
# -------------------------------------------------------------
us_rows <- us_R2_tab %>%
  transmute(
    Model     = model,
    `$R^2$ (in-sample)`      = fmt_pct(R2_in),
    `$R^2$ (out-of-sample)`  = fmt_pct(R2_oos)
  )
write_tabular(
  rows   = as.matrix(us_rows),
  header = colnames(us_rows),
  align  = "lrr",
  file   = "us_replication_R2.tex"
)

# -------------------------------------------------------------
# 11. Sample coverage: T_obs and date span per country
# -------------------------------------------------------------
coverage_rows <- panel %>%
  group_by(country) %>%
  summarise(
    T_obs = n(),
    start = min(date),
    end   = max(date),
    .groups = "drop"
  ) %>%
  arrange(country) %>%
  transmute(
    Country = country,
    Start   = format(start, "%Y-%m"),
    End     = format(end,   "%Y-%m"),
    `$T$ (months)` = fmt_int(T_obs)
  )
write_tabular(
  rows   = as.matrix(coverage_rows),
  header = colnames(coverage_rows),
  align  = "lllr",
  file   = "sample_coverage.tex"
)

cat(sprintf(
  "\nWrote %d figure PDFs to %s and %d LaTeX tables to %s.\n",
  length(plots), FIG_DIR, length(list.files(TAB_DIR, pattern = "\\.tex$")), TAB_DIR
))
