# presentation_output.R
# =============================================================
# Master-thesis mid-term presentation: build all figure PDFs and
# LaTeX tables that `presentation/main.tex` consumes via
# \includegraphics{...} and \input{...}.
#
# Run from the project root:
#   Rscript presentation_output.R
#
# Sources the full data pipeline (data preparation -> empirical
# regressions -> plot definitions) and then writes:
#   presentation/figures/*.pdf
#   presentation/tables/*.tex   (booktabs tabulars, no float wrapper)
# =============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(tibble)
})

OUT_DIR <- "presentation"
FIG_DIR <- file.path(OUT_DIR, "figures")
TAB_DIR <- file.path(OUT_DIR, "tables")
dir.create(FIG_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(TAB_DIR, recursive = TRUE, showWarnings = FALSE)

# -------------------------------------------------------------
# 1. Run the pipeline. Each script is sourced into the global
#    environment so downstream objects are visible.
# -------------------------------------------------------------
source("data preperation.R")
source("empirical.R")
source("plots.R")

# -------------------------------------------------------------
# 2. Save the plots that presentation/main.tex references.
#    Listed explicitly so a name mismatch errors loudly instead
#    of silently producing a presentation with missing figures.
# -------------------------------------------------------------
required_plots <- c(
  "yield_ts", "inflation_trend",
  "cycles_by_country", "local_cf", "gcf",
  "coef_eq19", "us_replication_R2", "r2_compare", "fitted_vs_realized",
  "trend_panel", "gdp_weights", "fxgcf_vs_gcf",
  "cf_corr_heatmap", "tstat_panel", "residual_acf_panel", "cf_oos_vs_in",
  # OOS factors and tests
  "gcf_oos_vs_in", "fxgcf_oos_vs_in", "oos_factors_combined",
  "oos_R2_compare", "cw_oos_tstat"
)

# Rebuild coef_eq19 here so it does not depend on plots.R having
# successfully assigned it (e.g. if tab_19 was missing at source time).
plots$coef_eq19 <- tab_19 %>%
  dplyr::filter(term %in% c("CF", "GCF"),
                !is.na(estimate), !is.na(std_err)) %>%
  dplyr::mutate(lo = estimate - 1.96 * std_err,
                hi = estimate + 1.96 * std_err) %>%
  ggplot2::ggplot(ggplot2::aes(country, estimate, colour = term)) +
  ggplot2::geom_pointrange(ggplot2::aes(ymin = lo, ymax = hi),
                           position = ggplot2::position_dodge(width = 0.5)) +
  ggplot2::geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50") +
  ggplot2::scale_colour_manual(values = c(CF = "#08519c", GCF = "#a50f15"),
                               name = NULL) +
  ggplot2::labs(title = "Eq (19): rx ~ CF + GCF coefficients (HAC +/- 1.96 SE)",
                subtitle = "Does the global CF subsume the local CF?",
                x = NULL, y = "Coefficient") +
  theme_thesis +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

missing_plots <- setdiff(required_plots, names(plots))
if (length(missing_plots) > 0) {
  stop("Missing plot definitions in `plots`: ",
       paste(missing_plots, collapse = ", "))
}

for (nm in required_plots) {
  ggplot2::ggsave(
    filename = file.path(FIG_DIR, paste0(nm, ".pdf")),
    plot     = plots[[nm]],
    width    = 9, height = 6
  )
}

# -------------------------------------------------------------
# 3. LaTeX-table helpers (no kableExtra dependency)
# -------------------------------------------------------------
fmt_num <- function(x, digits = 3) {
  ifelse(is.na(x), "--", formatC(x, format = "f", digits = digits))
}
fmt_pct <- function(x, digits = 1) {
  ifelse(is.na(x), "--", paste0(formatC(100 * x, format = "f", digits = digits), "\\%"))
}
fmt_int <- function(x) ifelse(is.na(x), "--", formatC(x, format = "d", big.mark = ","))
star <- function(p) {
  ifelse(is.na(p), "",
  ifelse(p < 0.01, "$^{***}$",
  ifelse(p < 0.05, "$^{**}$",
  ifelse(p < 0.10, "$^{*}$", ""))))
}

# Build a booktabs tabular (no caption / float -- wrap in beamer)
write_tabular <- function(rows, header, align, file) {
  body <- vapply(seq_len(nrow(rows)),
                 function(i) paste0(paste(rows[i, ], collapse = " & "), " \\\\"),
                 character(1))
  lines <- c(
    "% auto-generated by presentation_output.R; do not edit",
    sprintf("\\begin{tabular}{%s}", align),
    "\\toprule",
    paste0(paste(header, collapse = " & "), " \\\\"),
    "\\midrule",
    body,
    "\\bottomrule",
    "\\end{tabular}"
  )
  writeLines(lines, file.path(TAB_DIR, file))
}

# -------------------------------------------------------------
# 4. Eq (18): rx ~ CF, per country
# -------------------------------------------------------------
eq18_rows <- tab_18 %>%
  filter(term == "CF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\beta$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq),
    `$T$`    = fmt_int(T_obs)
  )

write_tabular(
  rows   = as.matrix(eq18_rows),
  header = colnames(eq18_rows),
  align  = "lrrrrr",
  file   = "eq18_local_cf.tex"
)

# -------------------------------------------------------------
# 5. Eq (20): rx ~ GCF, per country
# -------------------------------------------------------------
eq20_rows <- tab_20 %>%
  filter(term == "GCF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\gamma$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq),
    `$T$`    = fmt_int(T_obs)
  )
write_tabular(
  rows   = as.matrix(eq20_rows),
  header = colnames(eq20_rows),
  align  = "lrrrrr",
  file   = "eq20_global_cf.tex"
)

# -------------------------------------------------------------
# 6. Eq (19): rx ~ CF + GCF -- subsumption test per country
# -------------------------------------------------------------
eq19_wide <- tab_19 %>%
  filter(term %in% c("CF", "GCF")) %>%
  select(country, term, estimate, std_err, p_value, r_sq) %>%
  pivot_wider(names_from = term,
              values_from = c(estimate, std_err, p_value)) %>%
  left_join(
    nested_local_per_country %>% select(country, p_wald = p_value),
    by = "country"
  ) %>%
  arrange(country)

eq19_rows <- eq19_wide %>%
  transmute(
    Country = country,
    `$\\hat\\beta_{CF}$`   = paste0(fmt_num(estimate_CF, 3),  star(p_value_CF)),
    `(SE)`                 = paste0("(", fmt_num(std_err_CF, 3), ")"),
    `$\\hat\\gamma_{GCF}$` = paste0(fmt_num(estimate_GCF, 3), star(p_value_GCF)),
    `(SE) `                = paste0("(", fmt_num(std_err_GCF, 3), ")"),
    `$R^2$`                = fmt_pct(r_sq),
    `Wald $p$`             = fmt_num(p_wald, 3)
  )
write_tabular(
  rows   = as.matrix(eq19_rows),
  header = colnames(eq19_rows),
  align  = "lrrrrrr",
  file   = "eq19_subsumption.tex"
)

# -------------------------------------------------------------
# 7. Eq (22) & (23): USD investor view -- GCF and FXGCF
# -------------------------------------------------------------
eq22_rows <- tab_22 %>%
  filter(term == "GCF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\gamma$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq)
  )
write_tabular(
  rows   = as.matrix(eq22_rows),
  header = colnames(eq22_rows),
  align  = "lrrrr",
  file   = "eq22_usd_gcf.tex"
)

eq23_rows <- tab_23 %>%
  filter(term == "FXGCF") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\delta$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq)
  )
write_tabular(
  rows   = as.matrix(eq23_rows),
  header = colnames(eq23_rows),
  align  = "lrrrr",
  file   = "eq23_usd_fxgcf.tex"
)

# -------------------------------------------------------------
# 8. Pooled panel (Driscoll-Kraay): one row per spec
# -------------------------------------------------------------
pull_dk <- function(res, label, term) {
  ct <- res$coeftest
  if (!(term %in% rownames(ct))) {
    return(tibble(spec = label, term = term,
                  estimate = NA, se = NA, t = NA, p = NA))
  }
  tibble(
    spec     = label,
    term     = term,
    estimate = ct[term, "Estimate"],
    se       = ct[term, "Std. Error"],
    t        = ct[term, "t value"],
    p        = ct[term, "Pr(>|t|)"]
  )
}
panel_tbl <- bind_rows(
  pull_dk(panel_18, "Eq (18): rx $\\sim$ CF",            "CF"),
  pull_dk(panel_19, "Eq (19): rx $\\sim$ CF + GCF",      "CF"),
  pull_dk(panel_19, "Eq (19): rx $\\sim$ CF + GCF",      "GCF"),
  pull_dk(panel_20, "Eq (20): rx $\\sim$ GCF",           "GCF"),
  pull_dk(panel_21, "Eq (21): rx$^{USD}\\sim$ CF + GCF", "CF"),
  pull_dk(panel_21, "Eq (21): rx$^{USD}\\sim$ CF + GCF", "GCF"),
  pull_dk(panel_22, "Eq (22): rx$^{USD}\\sim$ GCF",      "GCF"),
  pull_dk(panel_23, "Eq (23): rx$^{USD}\\sim$ FXGCF",    "FXGCF")
)

panel_rows <- panel_tbl %>%
  transmute(
    Specification = spec,
    Term          = term,
    Estimate      = paste0(fmt_num(estimate, 3), star(p)),
    `DK SE`       = fmt_num(se, 3),
    `$t$`         = fmt_num(t, 2)
  )
write_tabular(
  rows   = as.matrix(panel_rows),
  header = colnames(panel_rows),
  align  = "llrrr",
  file   = "panel_dk.tex"
)

# -------------------------------------------------------------
# 9. Out-of-sample tests: Clark-West and Diebold-Mariano
# -------------------------------------------------------------
cw_rows <- bind_rows(
  cw_local %>% transmute(
    Country = country,
    Test    = "rx: GCF vs CF+GCF (CW)",
    `$\\Delta$MSPE-adj` = fmt_num(cw_mean, 4),
    `$t$`               = fmt_num(cw_t, 2),
    `$p$ (1-sided)`     = fmt_num(cw_p_one_sided, 3)
  ),
  cw_usd %>% transmute(
    Country = country,
    Test    = "rx$^{USD}$: GCF vs CF+GCF (CW)",
    `$\\Delta$MSPE-adj` = fmt_num(cw_mean, 4),
    `$t$`               = fmt_num(cw_t, 2),
    `$p$ (1-sided)`     = fmt_num(cw_p_one_sided, 3)
  )
) %>% arrange(Test, Country)

write_tabular(
  rows   = as.matrix(cw_rows),
  header = colnames(cw_rows),
  align  = "llrrr",
  file   = "oos_clark_west.tex"
)

dm_rows <- cw_fxgcf %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `DM mean ($e^2_{GCF}-e^2_{FXGCF}$)` = fmt_num(dm_mean, 4),
    `$t$`             = fmt_num(dm_t, 2),
    `$p$ (2-sided)`   = fmt_num(dm_p_two_sided, 3),
    `$n_{fcst}$`      = fmt_int(n_forecasts)
  )
write_tabular(
  rows   = as.matrix(dm_rows),
  header = colnames(dm_rows),
  align  = "lrrrr",
  file   = "oos_dm_fxgcf.tex"
)

# -------------------------------------------------------------
# 10. US replication: CP-2015 (CF) vs CP-2005 (forwards)
# -------------------------------------------------------------
us_rows <- us_R2_tab %>%
  transmute(
    Model     = model,
    `$R^2$ (in-sample)`      = fmt_pct(R2_in),
    `$R^2$ (out-of-sample)`  = fmt_pct(R2_oos)
  )
write_tabular(
  rows   = as.matrix(us_rows),
  header = colnames(us_rows),
  align  = "lrr",
  file   = "us_replication_R2.tex"
)

# -------------------------------------------------------------
# 11. Sample coverage: T_obs and date span per country
# -------------------------------------------------------------
coverage_rows <- panel %>%
  group_by(country) %>%
  summarise(
    T_obs = n(),
    start = min(date),
    end   = max(date),
    .groups = "drop"
  ) %>%
  arrange(country) %>%
  transmute(
    Country = country,
    Start   = format(start, "%Y-%m"),
    End     = format(end,   "%Y-%m"),
    `$T$ (months)` = fmt_int(T_obs)
  )
write_tabular(
  rows   = as.matrix(coverage_rows),
  header = colnames(coverage_rows),
  align  = "lllr",
  file   = "sample_coverage.tex"
)

# -------------------------------------------------------------
# 12. OOS factor tables: per-country Campbell-Thompson R²,
#     Clark-West with OOS factors, Diebold-Mariano on FXGCF_oos.
# -------------------------------------------------------------
oos_R2_wide <- oos_R2_tab %>%
  select(country, spec, R2_oos) %>%
  pivot_wider(names_from = spec, values_from = R2_oos) %>%
  arrange(country)

oos_R2_rows <- oos_R2_wide %>%
  transmute(
    Country               = country,
    `rx $\\sim$ CF$_{oos}$`        = fmt_pct(`rx ~ CF_oos`),
    `rx $\\sim$ GCF$_{oos}$`       = fmt_pct(`rx ~ GCF_oos`),
    `rx$^{USD}$ $\\sim$ GCF$_{oos}$`   = fmt_pct(`rx_USD ~ GCF_oos`),
    `rx$^{USD}$ $\\sim$ FXGCF$_{oos}$` = fmt_pct(`rx_USD ~ FXGCF_oos`)
  )
write_tabular(
  rows   = as.matrix(oos_R2_rows),
  header = colnames(oos_R2_rows),
  align  = "lrrrr",
  file   = "oos_R2_factors.tex"
)

cw_oos_rows <- bind_rows(
  cw_local_oos %>% transmute(
    Country = country,
    Test    = "rx",
    `$\\Delta$MSPE-adj` = fmt_num(cw_mean, 4),
    `$t$`               = fmt_num(cw_t, 2),
    `$p$ (1-sided)`     = fmt_num(cw_p_one_sided, 3),
    `$n_{fcst}$`        = fmt_int(n_forecasts)
  ),
  cw_usd_oos %>% transmute(
    Country = country,
    Test    = "rx$^{USD}$",
    `$\\Delta$MSPE-adj` = fmt_num(cw_mean, 4),
    `$t$`               = fmt_num(cw_t, 2),
    `$p$ (1-sided)`     = fmt_num(cw_p_one_sided, 3),
    `$n_{fcst}$`        = fmt_int(n_forecasts)
  )
) %>% arrange(Test, Country)

write_tabular(
  rows   = as.matrix(cw_oos_rows),
  header = colnames(cw_oos_rows),
  align  = "llrrrr",
  file   = "oos_clark_west_factors.tex"
)

dm_oos_rows <- dm_fxgcf_oos %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `DM mean ($e^2_{GCF_{oos}}-e^2_{FXGCF_{oos}}$)` = fmt_num(dm_mean, 4),
    `$t$`             = fmt_num(dm_t, 2),
    `$p$ (2-sided)`   = fmt_num(dm_p_two_sided, 3),
    `$n_{fcst}$`      = fmt_int(n_forecasts)
  )
write_tabular(
  rows   = as.matrix(dm_oos_rows),
  header = colnames(dm_oos_rows),
  align  = "lrrrr",
  file   = "oos_dm_fxgcf_factors.tex"
)

# -------------------------------------------------------------
# 13. OOS twin tables (mirror eq 18, 20, 19, 22, 23 with OOS factors)
# -------------------------------------------------------------
eq18_oos_rows <- tab_18_oos %>%
  filter(term == "CF_oos") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\beta$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq),
    `$T$`    = fmt_int(T_obs)
  )
write_tabular(rows = as.matrix(eq18_oos_rows), header = colnames(eq18_oos_rows),
              align = "lrrrrr", file = "eq18_local_cf_oos.tex")

eq20_oos_rows <- tab_20_oos %>%
  filter(term == "GCF_oos") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\gamma$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq),
    `$T$`    = fmt_int(T_obs)
  )
write_tabular(rows = as.matrix(eq20_oos_rows), header = colnames(eq20_oos_rows),
              align = "lrrrrr", file = "eq20_global_cf_oos.tex")

eq19_oos_wide <- tab_19_oos %>%
  filter(term %in% c("CF_oos", "GCF_oos")) %>%
  select(country, term, estimate, std_err, p_value, r_sq) %>%
  pivot_wider(names_from = term,
              values_from = c(estimate, std_err, p_value)) %>%
  left_join(
    nested_local_oos_per_country %>% select(country, p_wald = p_value),
    by = "country"
  ) %>%
  arrange(country)

eq19_oos_rows <- eq19_oos_wide %>%
  transmute(
    Country = country,
    `$\\hat\\beta_{CF^{oos}}$`    = paste0(fmt_num(estimate_CF_oos, 3),  star(p_value_CF_oos)),
    `(SE)`                        = paste0("(", fmt_num(std_err_CF_oos, 3), ")"),
    `$\\hat\\gamma_{GCF^{oos}}$`  = paste0(fmt_num(estimate_GCF_oos, 3), star(p_value_GCF_oos)),
    `(SE) `                       = paste0("(", fmt_num(std_err_GCF_oos, 3), ")"),
    `$R^2$`                       = fmt_pct(r_sq),
    `Wald $p$`                    = fmt_num(p_wald, 3)
  )
write_tabular(rows = as.matrix(eq19_oos_rows), header = colnames(eq19_oos_rows),
              align = "lrrrrrr", file = "eq19_subsumption_oos.tex")

eq22_oos_rows <- tab_22_oos %>%
  filter(term == "GCF_oos") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\gamma$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq)
  )
write_tabular(rows = as.matrix(eq22_oos_rows), header = colnames(eq22_oos_rows),
              align = "lrrrr", file = "eq22_usd_gcf_oos.tex")

eq23_oos_rows <- tab_23_oos %>%
  filter(term == "FXGCF_oos") %>%
  arrange(country) %>%
  transmute(
    Country  = country,
    `$\\hat\\delta$` = paste0(fmt_num(estimate, 3), star(p_value)),
    `HAC SE` = fmt_num(std_err, 3),
    `$t$`    = fmt_num(t_stat, 2),
    `$R^2$`  = fmt_pct(r_sq)
  )
write_tabular(rows = as.matrix(eq23_oos_rows), header = colnames(eq23_oos_rows),
              align = "lrrrr", file = "eq23_usd_fxgcf_oos.tex")

cat(sprintf(
  "\nWrote %d figure PDFs to %s and %d LaTeX tables to %s.\n",
  length(plots), FIG_DIR, length(list.files(TAB_DIR, pattern = "\\.tex$")), TAB_DIR
))
